import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';

type Language = 'uk' | 'en' | 'pl' | 'de';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  uk: {
    'dashboard.title': 'Головна',
    'dashboard.online': 'Користувачів в мережі',
    'dashboard.systemsOnline': 'Системи в нормі',
    'dashboard.welcome': 'Вітаємо,',
    'dashboard.morning': 'Доброго ранку',
    'dashboard.afternoon': 'Доброго дня',
    'dashboard.evening': 'Доброго вечора',
    'dashboard.threatPanel': 'ПАНЕЛЬ ЗАГРОЗ',
    'dashboard.filters': 'ФІЛЬТРИ',
    'footer.rights': '© Усі права захищено. 2026. Версія сайту:',
    'community.title': 'Стрічка та Обговорення',
    'community.latestPosts': 'Останні публікації',
    'event.title': 'Головна подія',
    'event.headTitle': 'ПОДІЇ',
    'event.subtitle': 'Активні квести, щоденні нагороди та івенти',
    'event.completed': 'Завершено',
    'event.operationSky': 'Операція:<br/>НЕБО 2026',
    'event.boost': 'БУСТ',
    'event.getReward': 'Отримуй нагороду',
    'profile.followers': 'Підписників',
    'profile.following': 'Підписок',
    'profile.follow': 'Підписатися',
    'profile.unfollow': 'Відписатися',
    'settings.title': 'Налаштування',
    'settings.account': 'Аккаунт',
    'settings.interface': 'Інтерфейс та сповіщення',
    'settings.brightness': 'Яскравість сторінки',
    'settings.navigation': 'Навігація',
    'settings.navPosition': 'Позиція панелі',
    'settings.navTop': 'Зверху',
    'settings.navBottom': 'Знизу',
    'settings.dynamicIsland': 'Dynamic Island',
    'settings.enable': 'Увімкнути',
    'settings.size': 'Розмір',
    'settings.sizeSmall': 'Малий',
    'settings.sizeMedium': 'Середній',
    'settings.sizeLarge': 'Великий',
    'settings.emoji': 'Емодзі',
    'settings.action': 'Дія (кнопка)',
    'settings.actionNone': 'Немає',
    'settings.actionCommunity': 'Стрічка',
    'settings.actionSearch': 'Пошук',
    'settings.actionDashboard': 'Дашборд',
    'settings.appearance': 'Оформлення',
    'settings.themeLight': 'Світла',
    'settings.themeDark': 'Темна',
    'settings.themeSystem': 'Системна',
    'settings.adminPanel': 'Панель Адміністратора',
    'settings.exitAdmin': 'Вийти з режиму адміністратора',
    'settings.language': 'Мова додатку',
    'settings.language.uk': 'Українська',
    'settings.language.en': 'English',
    'settings.language.pl': 'Polski',
    'settings.language.de': 'Deutsch',
    'settings.allowMessages': 'Дозволити повідомлення',
    'settings.allowMessagesDesc': 'Дозволити іншим користувачам надсилати вам повідомлення',
    'settings.email': 'Адреса електронної пошти',
    'settings.emailDesc': 'Електронну адресу неможливо змінити.',
    'settings.username': "Ім'я користувача",
    'settings.avatarUrl': 'Посилання на аватар (URL)',
    'settings.bannerUrl': 'Посилання на банер (URL)',
    'settings.bannerColor': 'Колір фону банера',
    'settings.cancel': 'Скасувати',
    'settings.save': 'Зберегти',
    'settings.saving': 'Збереження...',
    'settings.change': 'Змінити',
    'settings.unknownUser': 'Невідомий Користувач',
    'nav.dashboard': 'Дашборд',
    'nav.community': 'Стрічка',
    'nav.search': 'Пошук',
    'nav.profile': 'Профіль',
    'nav.settings': 'Налаштування',
    'nav.event': 'Івент',
    'nav.gifts': 'Подарунки',
    'nav.notifications': 'Уводи',
    'community.title': 'Спільнота',
    'community.subtitle': 'Остання інформація та обговорення',
    'community.tabs.all': 'Всі',
    'community.tabs.following': 'Підписки',
    'community.tabs.channels': 'Канали',
    'community.tabs.users': 'Користувачі',
    'community.createPost': 'Що нового?',
    'community.publish': 'Опублікувати',
    'community.pollTitle': 'Опитування',
    'community.pollOption': 'Варіант',
    'community.pollAddOption': 'Додати варіант',
    'community.addPhoto': 'Додати фото',
    'community.createPoll': 'Створити опитування',
    'community.createChannel': 'Створити канал',
    'community.searchUsers': 'Пошук користувачів...',
    'community.noChannels': 'Немає каналів',
    'community.createFirstChannel': 'Створіть перший канал!',
    'community.noPosts': 'Немає постів',
    'community.createFirstPost': 'Створіть перший пост!',
    'community.members': 'Учасників',
  },
  en: {
    'dashboard.title': 'Home',
    'dashboard.online': 'Users Online',
    'dashboard.systemsOnline': 'Systems Online',
    'dashboard.welcome': 'Welcome,',
    'dashboard.morning': 'Good morning',
    'dashboard.afternoon': 'Good afternoon',
    'dashboard.evening': 'Good evening',
    'dashboard.threatPanel': 'THREAT PANEL',
    'dashboard.filters': 'FILTERS',
    'footer.rights': '© All rights reserved. 2026. App Version:',
    'community.title': 'Feed & Discussions',
    'community.latestPosts': 'Latest Posts',
    'event.title': 'Main Event',
    'event.headTitle': 'EVENTS',
    'event.subtitle': 'Active quests, daily rewards and events',
    'event.completed': 'Completed',
    'event.operationSky': 'Operation:<br/>SKY 2026',
    'event.boost': 'BOOST',
    'event.getReward': 'Get your reward',
    'profile.followers': 'Followers',
    'profile.following': 'Following',
    'profile.follow': 'Follow',
    'profile.unfollow': 'Unfollow',
    'settings.title': 'Settings',
    'settings.account': 'Account',
    'settings.interface': 'Interface & Notifications',
    'settings.brightness': 'Page Brightness',
    'settings.navigation': 'Navigation',
    'settings.navPosition': 'Panel Position',
    'settings.navTop': 'Top',
    'settings.navBottom': 'Bottom',
    'settings.dynamicIsland': 'Dynamic Island',
    'settings.enable': 'Enable',
    'settings.size': 'Size',
    'settings.sizeSmall': 'Small',
    'settings.sizeMedium': 'Medium',
    'settings.sizeLarge': 'Large',
    'settings.emoji': 'Emoji',
    'settings.action': 'Action (button)',
    'settings.actionNone': 'None',
    'settings.actionCommunity': 'Feed',
    'settings.actionSearch': 'Search',
    'settings.actionDashboard': 'Dashboard',
    'settings.appearance': 'Appearance',
    'settings.themeLight': 'Light',
    'settings.themeDark': 'Dark',
    'settings.themeSystem': 'System',
    'settings.adminPanel': 'Admin Panel',
    'settings.exitAdmin': 'Exit Admin Mode',
    'settings.language': 'App Language',
    'settings.language.uk': 'Українська',
    'settings.language.en': 'English',
    'settings.language.pl': 'Polski',
    'settings.language.de': 'Deutsch',
    'settings.allowMessages': 'Allow Messages',
    'settings.allowMessagesDesc': 'Allow other users to send you messages',
    'settings.email': 'Email Address',
    'settings.emailDesc': 'Email address cannot be changed.',
    'settings.username': 'Username',
    'settings.avatarUrl': 'Avatar URL',
    'settings.bannerUrl': 'Banner URL',
    'settings.bannerColor': 'Banner Background Color',
    'settings.cancel': 'Cancel',
    'settings.save': 'Save',
    'settings.saving': 'Saving...',
    'settings.change': 'Change',
    'settings.unknownUser': 'Unknown User',
    'nav.dashboard': 'Dashboard',
    'nav.community': 'Feed',
    'nav.search': 'Search',
    'nav.profile': 'Profile',
    'nav.settings': 'Settings',
    'nav.event': 'Event',
    'nav.gifts': 'Gifts',
    'nav.notifications': 'Notifications',
    'community.title': 'Community',
    'community.subtitle': 'Latest information and discussions',
    'community.tabs.all': 'All',
    'community.tabs.following': 'Following',
    'community.tabs.channels': 'Channels',
    'community.tabs.users': 'Users',
    'community.createPost': 'What\'s new?',
    'community.publish': 'Publish',
    'community.pollTitle': 'Poll',
    'community.pollOption': 'Option',
    'community.pollAddOption': 'Add option',
    'community.addPhoto': 'Add photo',
    'community.createPoll': 'Create poll',
    'community.createChannel': 'Create channel',
    'community.searchUsers': 'Search users...',
    'community.noChannels': 'No channels',
    'community.createFirstChannel': 'Create your first channel!',
    'community.noPosts': 'No posts',
    'community.createFirstPost': 'Create your first post!',
    'community.members': 'Members',
  },
  pl: {
    'dashboard.title': 'Główna',
    'dashboard.online': 'Użytkownicy Online',
    'dashboard.systemsOnline': 'Systemy Online',
    'dashboard.welcome': 'Witaj,',
    'dashboard.morning': 'Dzień dobry',
    'dashboard.afternoon': 'Dzień dobry',
    'dashboard.evening': 'Dobry wieczór',
    'dashboard.threatPanel': 'PANEL ZAGROŻEŃ',
    'dashboard.filters': 'FILTRY',
    'footer.rights': '© Wszelkie prawa zastrzeżone. 2026. Wersja:',
    'community.title': 'Aktualności i Dyskusje',
    'community.latestPosts': 'Najnowsze posty',
    'event.title': 'Wydarzenie główne',
    'event.headTitle': 'WYDARZENIA',
    'event.subtitle': 'Aktywne zadania, codzienne nagrody i wydarzenia',
    'event.completed': 'Zakończone',
    'event.operationSky': 'Operacja:<br/>NIEBO 2026',
    'event.boost': 'WZMOCNIENIE',
    'event.getReward': 'Odbierz nagrodę',
    'profile.followers': 'Obserwujących',
    'profile.following': 'Obserwowanych',
    'profile.follow': 'Obserwuj',
    'profile.unfollow': 'Przestań obserwować',
    'settings.title': 'Ustawienia',
    'settings.account': 'Konto',
    'settings.interface': 'Interfejs i powiadomienia',
    'settings.brightness': 'Jasność strony',
    'settings.navigation': 'Nawigacja',
    'settings.navPosition': 'Pozycja panelu',
    'settings.navTop': 'Góra',
    'settings.navBottom': 'Dół',
    'settings.dynamicIsland': 'Dynamic Island',
    'settings.enable': 'Włącz',
    'settings.size': 'Rozmiar',
    'settings.sizeSmall': 'Mały',
    'settings.sizeMedium': 'Średni',
    'settings.sizeLarge': 'Duży',
    'settings.emoji': 'Emoji',
    'settings.action': 'Akcja (przycisk)',
    'settings.actionNone': 'Brak',
    'settings.actionCommunity': 'Aktualności',
    'settings.actionSearch': 'Szukaj',
    'settings.actionDashboard': 'Panel',
    'settings.appearance': 'Wygląd',
    'settings.themeLight': 'Jasny',
    'settings.themeDark': 'Ciemny',
    'settings.themeSystem': 'Systemowy',
    'settings.adminPanel': 'Panel Administratora',
    'settings.exitAdmin': 'Wyjdź z trybu administratora',
    'settings.language': 'Język aplikacji',
    'settings.language.uk': 'Українська',
    'settings.language.en': 'English',
    'settings.language.pl': 'Polski',
    'settings.language.de': 'Deutsch',
    'settings.allowMessages': 'Zezwalaj na wiadomości',
    'settings.allowMessagesDesc': 'Zezwól innym użytkownikom na wysyłanie Ci wiadomości',
    'settings.email': 'Adres e-mail',
    'settings.emailDesc': 'Adresu e-mail nie można zmienić.',
    'settings.username': 'Nazwa użytkownika',
    'settings.avatarUrl': 'URL awatara',
    'settings.bannerUrl': 'URL banera',
    'settings.bannerColor': 'Kolor tła banera',
    'settings.cancel': 'Anuluj',
    'settings.save': 'Zapisz',
    'settings.saving': 'Zapisywanie...',
    'settings.change': 'Zmień',
    'settings.unknownUser': 'Nieznany użytkownik',
    'nav.dashboard': 'Panel',
    'nav.community': 'Aktualności',
    'nav.search': 'Szukaj',
    'nav.profile': 'Profil',
    'nav.settings': 'Ustawienia',
    'nav.event': 'Wydarzenie',
    'nav.gifts': 'Prezenty',
    'nav.notifications': 'Powiadomienia',
    'community.title': 'Społeczność',
    'community.subtitle': 'Najnowsze informacje i dyskusje',
    'community.tabs.all': 'Wszystkie',
    'community.tabs.following': 'Subskrypcje',
    'community.tabs.channels': 'Kanały',
    'community.tabs.users': 'Użytkownicy',
    'community.createPost': 'Co nowego?',
    'community.publish': 'Opublikuj',
    'community.pollTitle': 'Ankieta',
    'community.pollOption': 'Opcja',
    'community.pollAddOption': 'Dodaj opcję',
    'community.addPhoto': 'Dodaj zdjęcie',
    'community.createPoll': 'Stwórz ankietę',
    'community.createChannel': 'Stwórz kanał',
    'community.searchUsers': 'Szukaj użytkowników...',
    'community.noChannels': 'Brak kanałów',
    'community.createFirstChannel': 'Stwórz pierwszy kanał!',
    'community.noPosts': 'Brak postów',
    'community.createFirstPost': 'Stwórz pierwszy post!',
    'community.members': 'Członkowie',
  },
  de: {
    'dashboard.title': 'Startseite',
    'dashboard.online': 'Benutzer Online',
    'dashboard.systemsOnline': 'Systeme Online',
    'dashboard.welcome': 'Willkommen,',
    'dashboard.morning': 'Guten Morgen',
    'dashboard.afternoon': 'Guten Tag',
    'dashboard.evening': 'Guten Abend',
    'dashboard.threatPanel': 'BEDROHUNGSPANEL',
    'dashboard.filters': 'FILTER',
    'footer.rights': '© Alle Rechte vorbehalten. 2026. Version:',
    'community.title': 'Feed & Diskussionen',
    'community.latestPosts': 'Neueste Beiträge',
    'event.title': 'Hauptereignis',
    'event.headTitle': 'VERANSTALTUNGEN',
    'event.subtitle': 'Aktive Quests, tägliche Belohnungen und Events',
    'event.completed': 'Abgeschlossen',
    'event.operationSky': 'Operation:<br/>HIMMEL 2026',
    'event.boost': 'BOOST',
    'event.getReward': 'Hol dir deine Belohnung',
    'profile.followers': 'Follower',
    'profile.following': 'Folge ich',
    'profile.follow': 'Folgen',
    'profile.unfollow': 'Entfolgen',
    'settings.title': 'Einstellungen',
    'settings.account': 'Konto',
    'settings.interface': 'Benutzeroberfläche & Benachrichtigungen',
    'settings.brightness': 'Seitenhelligkeit',
    'settings.navigation': 'Navigation',
    'settings.navPosition': 'Panel-Position',
    'settings.navTop': 'Oben',
    'settings.navBottom': 'Unten',
    'settings.dynamicIsland': 'Dynamic Island',
    'settings.enable': 'Aktivieren',
    'settings.size': 'Größe',
    'settings.sizeSmall': 'Klein',
    'settings.sizeMedium': 'Mittel',
    'settings.sizeLarge': 'Groß',
    'settings.emoji': 'Emoji',
    'settings.action': 'Aktion (Schaltfläche)',
    'settings.actionNone': 'Keine',
    'settings.actionCommunity': 'Feed',
    'settings.actionSearch': 'Suche',
    'settings.actionDashboard': 'Dashboard',
    'settings.appearance': 'Erscheinungsbild',
    'settings.themeLight': 'Hell',
    'settings.themeDark': 'Dunkel',
    'settings.themeSystem': 'System',
    'settings.adminPanel': 'Admin-Panel',
    'settings.exitAdmin': 'Admin-Modus beenden',
    'settings.language': 'App-Sprache',
    'settings.language.uk': 'Українська',
    'settings.language.en': 'English',
    'settings.language.pl': 'Polski',
    'settings.language.de': 'Deutsch',
    'settings.allowMessages': 'Nachrichten erlauben',
    'settings.allowMessagesDesc': 'Erlauben Sie anderen Benutzern, Ihnen Nachrichten zu senden',
    'settings.email': 'E-Mail-Adresse',
    'settings.emailDesc': 'Die E-Mail-Adresse kann nicht geändert werden.',
    'settings.username': 'Benutzername',
    'settings.avatarUrl': 'Avatar-URL',
    'settings.bannerUrl': 'Banner-URL',
    'settings.bannerColor': 'Banner-Hintergrundfarbe',
    'settings.cancel': 'Abbrechen',
    'settings.save': 'Speichern',
    'settings.saving': 'Speichern...',
    'settings.change': 'Ändern',
    'settings.unknownUser': 'Unbekannter Benutzer',
    'nav.dashboard': 'Dashboard',
    'nav.community': 'Feed',
    'nav.search': 'Suche',
    'nav.profile': 'Profil',
    'nav.settings': 'Einstellungen',
    'nav.event': 'Ereignis',
    'nav.gifts': 'Geschenke',
    'nav.notifications': 'Benachrichtigungen',
    'community.title': 'Gemeinschaft',
    'community.subtitle': 'Neueste Informationen und Diskussionen',
    'community.tabs.all': 'Alle',
    'community.tabs.following': 'Abonnements',
    'community.tabs.channels': 'Kanäle',
    'community.tabs.users': 'Benutzer',
    'community.createPost': 'Was gibt\'s Neues?',
    'community.publish': 'Veröffentlichen',
    'community.pollTitle': 'Umfrage',
    'community.pollOption': 'Möglichkeit',
    'community.pollAddOption': 'Option hinzufügen',
    'community.addPhoto': 'Foto hinzufügen',
    'community.createPoll': 'Umfrage erstellen',
    'community.createChannel': 'Kanal erstellen',
    'community.searchUsers': 'Benutzer suchen...',
    'community.noChannels': 'Keine Kanäle',
    'community.createFirstChannel': 'Erstelle deinen ersten Kanal!',
    'community.noPosts': 'Keine Beiträge',
    'community.createFirstPost': 'Erstelle deinen ersten Beitrag!',
    'community.members': 'Mitglieder',
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem('appLanguage');
    return (saved as Language) || 'uk';
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('appLanguage', lang);
  };

  const t = (key: string): string => {
    return translations[language]?.[key] || translations['uk']?.[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
